require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InventoryitemsController do

  # This should return the minimal set of attributes required to create a valid
  # Inventoryitem. As you add validations to Inventoryitem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InventoryitemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all inventoryitems as @inventoryitems" do
      inventoryitem = Inventoryitem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:inventoryitems).should eq([inventoryitem])
    end
  end

  describe "GET show" do
    it "assigns the requested inventoryitem as @inventoryitem" do
      inventoryitem = Inventoryitem.create! valid_attributes
      get :show, {:id => inventoryitem.to_param}, valid_session
      assigns(:inventoryitem).should eq(inventoryitem)
    end
  end

  describe "GET new" do
    it "assigns a new inventoryitem as @inventoryitem" do
      get :new, {}, valid_session
      assigns(:inventoryitem).should be_a_new(Inventoryitem)
    end
  end

  describe "GET edit" do
    it "assigns the requested inventoryitem as @inventoryitem" do
      inventoryitem = Inventoryitem.create! valid_attributes
      get :edit, {:id => inventoryitem.to_param}, valid_session
      assigns(:inventoryitem).should eq(inventoryitem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Inventoryitem" do
        expect {
          post :create, {:inventoryitem => valid_attributes}, valid_session
        }.to change(Inventoryitem, :count).by(1)
      end

      it "assigns a newly created inventoryitem as @inventoryitem" do
        post :create, {:inventoryitem => valid_attributes}, valid_session
        assigns(:inventoryitem).should be_a(Inventoryitem)
        assigns(:inventoryitem).should be_persisted
      end

      it "redirects to the created inventoryitem" do
        post :create, {:inventoryitem => valid_attributes}, valid_session
        response.should redirect_to(Inventoryitem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inventoryitem as @inventoryitem" do
        # Trigger the behavior that occurs when invalid params are submitted
        Inventoryitem.any_instance.stub(:save).and_return(false)
        post :create, {:inventoryitem => {}}, valid_session
        assigns(:inventoryitem).should be_a_new(Inventoryitem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Inventoryitem.any_instance.stub(:save).and_return(false)
        post :create, {:inventoryitem => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inventoryitem" do
        inventoryitem = Inventoryitem.create! valid_attributes
        # Assuming there are no other inventoryitems in the database, this
        # specifies that the Inventoryitem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Inventoryitem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => inventoryitem.to_param, :inventoryitem => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested inventoryitem as @inventoryitem" do
        inventoryitem = Inventoryitem.create! valid_attributes
        put :update, {:id => inventoryitem.to_param, :inventoryitem => valid_attributes}, valid_session
        assigns(:inventoryitem).should eq(inventoryitem)
      end

      it "redirects to the inventoryitem" do
        inventoryitem = Inventoryitem.create! valid_attributes
        put :update, {:id => inventoryitem.to_param, :inventoryitem => valid_attributes}, valid_session
        response.should redirect_to(inventoryitem)
      end
    end

    describe "with invalid params" do
      it "assigns the inventoryitem as @inventoryitem" do
        inventoryitem = Inventoryitem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Inventoryitem.any_instance.stub(:save).and_return(false)
        put :update, {:id => inventoryitem.to_param, :inventoryitem => {}}, valid_session
        assigns(:inventoryitem).should eq(inventoryitem)
      end

      it "re-renders the 'edit' template" do
        inventoryitem = Inventoryitem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Inventoryitem.any_instance.stub(:save).and_return(false)
        put :update, {:id => inventoryitem.to_param, :inventoryitem => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inventoryitem" do
      inventoryitem = Inventoryitem.create! valid_attributes
      expect {
        delete :destroy, {:id => inventoryitem.to_param}, valid_session
      }.to change(Inventoryitem, :count).by(-1)
    end

    it "redirects to the inventoryitems list" do
      inventoryitem = Inventoryitem.create! valid_attributes
      delete :destroy, {:id => inventoryitem.to_param}, valid_session
      response.should redirect_to(inventoryitems_url)
    end
  end

end
